Javascript Library app
Samkiroko/library_app_js pull request #1
Opened 2020-07-08 22:44 UTC by Samkiroko

- Used Javascript prototypes to create functions
- Used Bootswatch for CSS(base on boostrap) for styling
- Used localStorage to keep data persistent

2020-07-09 06:47 UTC, bellom requested changes
## Hi @Samkiroko  :clap: 

### Awesome Design, Good job so far!! :+1: 

**Quick One:** _**This project is one of the collaborative projects but you're working alone, may I ask why. kindly drop your answer in here for other TSE to see, thanks.**_

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-09 06:47 UTC, bellom commented on app.js
> +    div.className = `alert alert-${className}`;
Let's separate the DOM from application logic, you can create another file for DOM

![image](https://user-images.githubusercontent.com/31897434/87004592-9027f300-c1b5-11ea-9e2d-6617ca2c92b2.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-07-09 06:47 UTC, bellom commented on index.html
> +      </form>
According to the project requirement, you're supposed to have a `button` that will bring up the form and users should be able to specify the status of the book either read or unread in the form.

![image](https://user-images.githubusercontent.com/31897434/87005140-75a24980-c1b6-11ea-99db-ce603083bd6b.png)

https://www.theodinproject.com/courses/javascript/lessons/library

2020-07-09 06:47 UTC, bellom commented on index.html
> +        <tbody id="book-list"></tbody>
From your app;


According to the project requirement, you're supposed to have a toggle feature, where users can change the book status.

![image](https://user-images.githubusercontent.com/31897434/87005323-bbf7a880-c1b6-11ea-8d55-43d445f87e8c.png)

https://www.theodinproject.com/courses/javascript/lessons/library

2020-07-09 06:47 UTC, bellom commented on index.html
> +          <input type="text" id="page" class="form-control" />
Opps, you set the input page number to text, kindly validate this, users should not be able to enter non-digit data.
![image](https://user-images.githubusercontent.com/31897434/87005702-5526bf00-c1b7-11ea-9e16-cf34f178bf75.png)

2020-07-09 18:19 UTC, Samkiroko commented
- I hand to work on almost a new UI but do all requested changes
- WHY am submitting the project alone: 
**I have been sick for the last two week and my partner is ahead of me, hope I will catch up**

2020-07-09 20:12 UTC, Forison requested changes
## Changes Required❌
# 🙋‍♂️ Samuel 
#### You have done a good job so far, however, some of the issues raised in the previous review still persist👨‍💼.
* [x]  There should be a new book button that brings up a form.
- As mentioned in the previous review, the should be an additional book button which on click brings up the book addition form, which is initially hidden until the button is clicked.
* [x] Kindly set an input validation on the number pages to make sure your number of pages only accepts a number. 
- Currently, "Number of pages" can be a string. Check the image below👇
![check](https://user-images.githubusercontent.com/29695661/87084940-0dc32180-c1fd-11ea-8fd9-67b97c6efb91.png)
- Kindly do the same for the read status, In the case of the status, a dropdown would be the best as the approach.

**[OPTIONAL]** 
* [ ] Th nature of the code in the app.js makes the reading of the code very hard variables, mixed with classes and functions. I would suggest you separate them and require/import when needed. This enhances code readability and future improvements.
* [ ] The UI can be improved and made more appealing, you can even add a picture of the book.
* [ ] Kindly add a description to the repository, this makes the repository more professional.
> Remember recruiters may ask you to submit some of the projects you have worked on during your job search. Having a good UI enhances and a description to all your repos is can be a plus.
### That is it, kindly make the changes and submit the project for a re-review🤗.
#### Happy coding😎
Addo Forison👨‍💻

2020-07-09 21:53 UTC, Samkiroko commented
- @Forison I think you have checked the wrong PR.
- all the change that was requested I have done.
- Also, I have  UI as per the Readme file link: [LIVE DEMO](https://quizzical-yonath-9ac08b.netlify.app/)
- Added the validation

2020-07-09 22:41 UTC, Forison commented
> * @Forison I think you have checked the wrong PR.
> * all the change that was requested I have done.
> * Also, I have  UI as per the Readme file link: [LIVE DEMO](https://quizzical-yonath-9ac08b.netlify.app/)
> * Added the validation

@Samkiroko I don't think I have the wrong branch, the other branches ie master and development are even empty so they have nothing to show. I was trying to reach you on slack to see the source error but it seems you are not available currently. I will record and attached a video for the step to access the project as stated in the readme. My local machine's output is very different from the page you have in the live demo. I find this very strange. Kindly contact me on slack for further discussions on this.

2020-07-14 19:17 UTC, Oghenebrume50 approved these changes
### APPROVED 

Hi @Samkiroko this looks good to me, kudos for making changes please merge and move on :+1: 

**RAPHAEL NORIODE** :mask:

2020-07-14 22:12 UTC, merged